#SPDX-License-Identifier: MIT-0
---
# tasks file for os_update

# This role will be used to perform updates on the OS. 

# Updating Ubuntu
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
  when: ansible_distribution == "Ubuntu"
  become: true

# Updating Windows
- name: Install all security, critical, and rollup updates without a scheduled task
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
  become: true
  become_method: runas
  become_user: SYSTEM
  when: ansible_distribution == "Ubuntu"