#SPDX-License-Identifier: MIT-0
---
# tasks file for install_wireshark_from_local
# - name: Install Wireshark from a local copy
#   ansible.windows.win_package:
#     name: "Wireshark"
#     state: present
#   when: ansible_distribution == "Microsoft Windows Server 2022 Standard"
#   # hosts: windows
#   # gather_facts: yes
  
- name: Copy Wireshark installer to the remote host
  win_copy:
    src: Wireshark-4.4.5-x64.exe   # Path to the installer on the control machine
    dest: C:\Temp\Wireshark-4.4.5-x64.exe         # Destination path on the remote machine

- name: Install Wireshark silently
  win_command: C:\Temp\Wireshark-4.4.5-x64.exe /S /D=C:\Program Files\Wireshark
  args:
    creates: C:\Program Files\Wireshark\Wireshark.exe  # Prevents reinstallation if Wireshark is already installed

- name: Remove the installer after installation
  win_file:
    path: C:\Temp\Wireshark-4.4.5-x64.exe
    state: absent
