---
# ============================================================
# Play 1: Windows — Upload and set desktop wallpaper
# ============================================================

- name: Upload and set Windows desktop wallpaper
  hosts: all
  vars:
    wallpaper_filename: "new-desktop.jpg"
    remote_wallpaper_path: "C:\\Users\\Public\\Pictures\\{{ wallpaper_filename }}"

  tasks:
    - name: Upload the wallpaper to Windows
      ansible.windows.win_copy:
        src: "{{ wallpaper_filename }}"
        dest: "{{ remote_wallpaper_path }}"
        remote_src: no
      when: ansible_os_family == "Windows"

    - name: Set desktop wallpaper using PowerShell
      ansible.windows.win_shell: |
        $path = "{{ remote_wallpaper_path }}"
        $regPath = "HKCU:\Control Panel\Desktop"
        Set-ItemProperty -Path $regPath -Name Wallpaper -Value $path
        Set-ItemProperty -Path $regPath -Name WallpaperStyle -Value 2
        Set-ItemProperty -Path $regPath -Name TileWallpaper -Value 0
        RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters
        gpupdate /force
      when: ansible_os_family == "Windows"

# ============================================================
# Play 2: Kali Linux — Upload and set GNOME wallpaper
# ============================================================


- name: Upload image and set Kali login background
  hosts: i82_kali
  become: yes
  vars:
    wallpaper_filename: "new-desktopRT.jpg"
    remote_image_path: /usr/share/backgrounds/custom-kali-login.png
  tasks:
    - name: Upload local image to remote host
      copy:
        src: "{{ wallpaper_filename }}"    
        dest: "{{ remote_image_path }}"
        owner: root
        group: root
        mode: '0644'

    - name: Create symlink for the login background
      file:
        src: "{{ remote_image_path }}"
        dest: /usr/share/desktop-base/kali-theme/login/background


        state: link
        force: yes



