---

- hosts: linux
  tasks:
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

# - name: Install wireshark
#   hosts: windows
#   roles:
#     - install_wireshark_from_local


- name: Preparing Windows for Chocolatey
  hosts: windows
  roles:
    - install_chocolatey
    # - install_ninite
    # - darkwizard242.googlechrome
  #when: ansible_distribution == "Microsoft Windows Server 2022 Standard"

- hosts: windows
  tasks:
  - name: Disable Windows Updates Service
    win_service:
      name: wuauserv
      state: stopped
    when: ansible_distribution == "Microsoft Windows Server 2022 Standard"

- name: Configuring the database Servers
  hosts: db_servers
  roles:
    - install_mysql

- name: Configuring the nginx servers
  hosts: web_servers:&linux
  roles:
    - install_nginx
    
- name: Configuring the iis Servers
  hosts: web_servers:&windows
  roles:
    - install_iis

- name: Configuring the File Servers
  hosts: file_server
  roles:
    - file_server
    
- name: Adding Windows windows to server
  hosts: windows
  roles:
    - add_users

- name: Adding Linux users to server
  hosts: linux
  roles:
    - add_users

