---

- hosts: all
  tasks:

  - name: Install all security, critical, and rollup updates without a scheduled task
    ansible.windows.win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      reboot: true
      state: installed
    become: true
    become_method: runas
    become_user: SYSTEM
    # reboot: 
    when: ansible_os_family == "Windows"


  - name: Install updates on Linux
    ansible.builtin.apt:
      name: "*"
      state: latest
    when: ansible_os_family == "Windows"

    