---

- hosts: linux
  tasks:
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: windows
  tasks:
  - name: Disable Windows Updates Service
    win_service:
      name: wuauserv
      state: stopped
    when: ansible_distribution == "Microsoft Windows Server 2022 Standard"

- hosts: web_servers:&linux
  tasks:
  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers:&windows
  tasks:
  - name: install IIS
    win_feature:
      name: "Web-Server"
      state: present
      restart: yes
      include_sub_features: yes
      include_management_tools: yes
    when: ansible_distribution == "Microsoft Windows Server 2022 Standard"
