---
- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Create images directory
  ansible.builtin.file:
    path: "/var/www/html/images"
    state: directory
    mode: '0755'
  when: ansible_distribution == "Ubuntu"

- name: Upload image to webserver
  ansible.builtin.copy:
    src: my_image.jpeg
    dest: "/var/www/html/images/my_image.jpeg"
    mode: '0644'
  when: ansible_distribution == "Ubuntu"

- name: Deploy custom index page
  ansible.builtin.template:
    src: default_site.html.j2
    dest: "/var/www/html/index.html"
    mode: '0644'
  when: ansible_distribution == "Ubuntu"